import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import twoFactorRouter from "./twoFactor";
import signingKeyRouter from "./signingKey";
import attestationRouter from "./attestation";
import usersRouter from "./users";
import eventsRouter from "./events";
import braceletsRouter from "./bracelets";
import topupsRouter from "./topups";
import merchantsRouter from "./merchants";
import locationsRouter from "./locations";
import productsRouter from "./products";
import inventoryRouter from "./inventory";
import stockMovementsRouter from "./stockMovements";
import restockOrdersRouter from "./restockOrders";
import transactionsRouter from "./transactions";
import splitPaymentsRouter from "./splitPayments";
import payoutsRouter from "./payouts";
import reportsRouter from "./reports";
import promoterCompaniesRouter from "./promoterCompanies";
import refundsRouter from "./refunds";
import analyticsRouter from "./analytics";
import fraudAlertsRouter from "./fraudAlerts";
import storageRouter from "./storage";
import bankAttendeeRouter from "./bankAttendee";
import accessZonesRouter from "./accessZones";
import ticketingRouter from "./ticketing";
import ticketCheckinRouter from "./ticketCheckin";
import gateTicketRouter from "./gateTicket";
import guestListsRouter from "./guestLists";
import whatsappTemplatesRouter from "./whatsappTemplates";
import auditorRouter from "./auditor";
import devicesRouter from "./devices";
import boxOfficeSaleRouter from "./boxOfficeSale";
import syncIssuesRouter from "./syncIssues";
import loadTestRouter from "./loadTest";
import productCategoriesRouter from "./productCategories";
import localServersRouter from "./localServers";
import adsRouter from "./ads";
import citiesRouter from "./cities";
import aiRouter from "./ai";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(twoFactorRouter);
router.use(attestationRouter);
router.use(signingKeyRouter);
router.use(usersRouter);
router.use(eventsRouter);
router.use(braceletsRouter);
router.use(topupsRouter);
router.use(merchantsRouter);
router.use(locationsRouter);
router.use(productsRouter);
router.use(inventoryRouter);
router.use(stockMovementsRouter);
router.use(restockOrdersRouter);
router.use(transactionsRouter);
router.use(splitPaymentsRouter);
router.use(payoutsRouter);
router.use(reportsRouter);
router.use(promoterCompaniesRouter);
router.use(refundsRouter);
router.use(analyticsRouter);
router.use(fraudAlertsRouter);
router.use(storageRouter);
router.use(bankAttendeeRouter);
router.use(accessZonesRouter);
router.use(ticketingRouter);
router.use(ticketCheckinRouter);
router.use(gateTicketRouter);
router.use(guestListsRouter);
router.use(whatsappTemplatesRouter);
router.use(auditorRouter);
router.use(devicesRouter);
router.use(boxOfficeSaleRouter);
router.use(syncIssuesRouter);
router.use(loadTestRouter);
router.use(productCategoriesRouter);
router.use(localServersRouter);
router.use(adsRouter);
router.use(citiesRouter);
router.use(aiRouter);

export default router;
